### ISSUE TITLE
Update documentation for Debian packaging

### ISSUE THREAD

**Issue by mblayman** [mblayman/tappy#10]
@cans, if you get tappy packaged in Debian, I would love to update the documentation to mention `apt-get install tappy` (or `python-tappy` or whatever it gets called) as an installation method. It will help recognize your work and benefit the project as an easy install method.

**Comment by cans** [comment]
Hi Matt,

  I would be very happy about that, but not being a Debian Developer, I
have yet to find a sponsor willing to upload the package into the Debian
archive. I have to make a more insistant appeal to find one in Debian
mailing lists, but I also just changed job and am in the process of moving
(everything happened pretty fast) and I am currently cut off some of the
latest changes I made and will be for the next two weeks (nothing major, if
I remember correctly there is only a typo I found in the man page I wrote
and an improved description of what the package provides). All this to say
that what you are suggesting may still be a bit premature (functioning
packages are available there: http://www.caniart.net/debian/NEW/, but this
not a debian repository). I will keep you up to date. Thanks for your
patience and sorry for the unconvenience.

Regards,
Nicolas.

**Comment by mblayman** [comment]
That's no problem at all. I'm not in any rush (after all, I don't mind doing `pip install tap.py` :smile: ). Even if you won't be able to get it into Debian yourself, your work so far has helped to push it in the right direction. Thanks again!

**Comment by mblayman** [comment]
We can document if/when something gets into Debian. Feel free to let me know when that happens and I'll be happy to write something up.
