### ISSUE TITLE
tappy script should read from a stream

### ISSUE THREAD

**Issue by mblayman** [mblayman/tappy#20]
The `tappy` script is only capable of reading from files right now. It should learn how to read from streams too.

**Comment by blakev** [comment]
What do you mean by this?

Read code from a stream? Read test results from a stream for parsing?

**Comment by mblayman** [comment]
Thanks for the question. I guess I was unclear. In a nutshell, I would like something like the following to work:

```bash
$ nosetests --with-tap --tap-stream | tappy
................F..................................
======================================================================
FAIL: <file=TestParser.tap>
- The parser extracts a bail out line.
----------------------------------------------------------------------

----------------------------------------------------------------------
Ran 51 tests in 0.002s

FAILED (failures=1)
```

There are TAP producers that can send TAP results directly to the output stream (e.g., using the nosetests plugin with `--tap-stream`). The `tappy` TAP consumer can only currently read files passed in as arguments instead of connecting to the stdout stream via a pipe. I want to make `tappy` work with piping. You can see on the TAP website that this is a desired characteristic of TAP consumers (http://testanything.org/consumers.html).

I hope that clears things up.

**Comment by blakev** [comment]
Yeah, perfectly, thanks!

We're getting ready to use this plugin on a maturing test suite and it's going to need a few tweaks to fit our use case. I'll probably be working through your code extensively and want to clean up the "Issues" along the way :)

**Comment by mblayman** [comment]
Cool. I certainly know this code inside and out so if you find something and you want to open an issue about it, feel free to do so and we can get a dialog going.
