### ISSUE TITLE
Allow the TAP producer to write a stack trace as part of the output

### ISSUE THREAD

**Issue by chutsu** [mblayman/tappy#5]
More of a feature than an issue, I know it is not required to output the stack trace, but it would be nice to have it.

**Comment by mblayman** [comment]
I think the code is in a good position to do this now. My plan is to add a `diagnostic` to the `Result` line class.

In `unittest` and `nose`, there is good access to the raw traceback object. When these test tools call, `tracker.add_not_ok`, they can do some formatting on the traceback object via the traceback module (specifically, `traceback.format_exception`).

This will be harder to do for pytest so I'll track that in a separate issue.
